const state={crystals:1250,avatar:"🧙",prices:{crystals100:["100 ✦",70],crystals500:["500 ✦",330],crystals1000:["1 000 ✦",670],crystals5000:["5 000 ✦",3330],crystals10000:["10 000 ✦",6660],vip:["VIP на 30 дней",100],crown:["Корона на 30 дней",150],divine:["Божественная на 30 дней",300],battlepass:["Battle Pass Premium",799],starter:["Набор новичка",330]}};
const screens=[...document.querySelectorAll('.screen')],navs=[...document.querySelectorAll('.nav')],toast=document.getElementById('toast');
function showScreen(name){screens.forEach(s=>s.classList.toggle('active',s.id===name));navs.forEach(n=>n.classList.toggle('active',n.dataset.action===name));window.scrollTo({top:0,behavior:'smooth'});}
function notify(text){toast.textContent=text;toast.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>toast.classList.remove('show'),2200);}
function buy(key){const item=state.prices[key];if(!item)return;notify(`${item[0]} · ${item[1]} ★ — готово к оплате`);}
function setAvatar(a){state.avatar=a;['profileAvatar','homeAvatar','previewAvatar','miniAvatar','battlePlayerAvatar'].forEach(id=>{const el=document.getElementById(id);if(el)el.textContent=a});document.querySelectorAll('.avatar-choice').forEach(b=>b.classList.toggle('selected',b.dataset.avatar===a));notify('Аватар сохранён');}
let enemy=72;function attack(skill=false){const damage=skill?720:347;enemy=Math.max(0,enemy-(skill?8:5));const bar=document.getElementById('enemyHp');bar.style.width=enemy+'%';document.getElementById('enemyHpText').textContent=`${Math.round(enemy/100*10000).toLocaleString('ru-RU')} / 10 000 HP`;const log=document.getElementById('combatLog');log.classList.remove('hit');void log.offsetWidth;log.classList.add('hit');log.textContent=skill?`✨ РАЗРЫВ! Критический эффект · −${damage} HP`:`⚔️ Атака нанесла −${damage} HP`;navigator.vibrate?.(skill?[40,30,80]:25);if(enemy===0){log.textContent='🏆 ХРАНИТЕЛЬ ПОВЕРЖЕН! +1 240 DKR · +380 XP';enemy=100;setTimeout(()=>{document.getElementById('enemyHp').style.width='100%';document.getElementById('enemyHpText').textContent='10 000 / 10 000 HP'},900)}}
document.addEventListener('click',e=>{const avatar=e.target.closest('[data-avatar]');if(avatar){setAvatar(avatar.dataset.avatar);return}const el=e.target.closest('[data-action],[data-buy]');if(!el)return;const action=el.dataset.action;if(action){if(action==='profile'||action==='home'||action==='pass'||action==='crystals'||action==='privileges'||action==='battle')showScreen(action);if(action==='demoBattle')showScreen('battle');if(action==='attack')attack(false);if(action==='skill')attack(true)}if(el.dataset.buy)buy(el.dataset.buy)});
function renderBalance(){const t=state.crystals.toLocaleString('ru-RU');document.getElementById('crystalBalance').textContent=t;document.getElementById('crystalBalanceLarge').textContent=t}renderBalance();
